package hr.fer.android.jmbag0036485175;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.widget.Button;
import android.widget.TextView;

/**
 * {@code DisplayActivity} displays the message generated by the {@link CalculusActivity},
 * which is either the result or an error message.<br>
 * Option for sending the message via an email is available.
 *
 * @author Dan
 */
public class DisplayActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_display);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        TextView tvMessage = (TextView) findViewById(R.id.tvMessage);

        String message = getIntent().getExtras().getString(getString(R.string.result), "");
        tvMessage.setText(message);

        Button btnOK = (Button) findViewById(R.id.btnOK);
        btnOK.setOnClickListener(v -> {
            Intent i = new Intent();
            setResult(RESULT_OK, i);
            finish();
        });

        Button btnSendEmail = (Button) findViewById(R.id.btnSendEmail);
        btnSendEmail.setOnClickListener(v -> {
            Intent emailIntent = new Intent(Intent.ACTION_SENDTO);
            emailIntent.setData(Uri.parse("mailto:"));
            emailIntent.putExtra(Intent.EXTRA_EMAIL, new String[]{getString(R.string.email_address)});
            emailIntent.putExtra(Intent.EXTRA_SUBJECT, getString(R.string.email_subject));
            emailIntent.putExtra(Intent.EXTRA_TEXT, message);
            if (emailIntent.resolveActivity(getPackageManager()) != null) {
                startActivity(emailIntent);
            }
        });
    }

}
